# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileType', models.CharField(choices=[('P', 'P&L File'), ('K', 'Key File'), ('T', 'Transactions Data File')], default='K', max_length=1)),
                ('FileName', models.CharField(max_length=20)),
                ('TheActualFile', models.FileField(upload_to='')),
                ('FileDescription', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RunSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=100)),
                ('RunNo', models.IntegerField()),
                ('RunName', models.CharField(max_length=20)),
                ('RunDescription', models.TextField(blank=True)),
            ],
            options={
                'permissions': (('file_owner', 'File Owner'), ('file_edit_permission', 'File Editing Permission'), ('file_view_permission', 'File Viewing Permission')),
            },
        ),
        migrations.AddField(
            model_name='filespace',
            name='UniqueRunID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.RunSpace'),
        ),
    ]
