# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-28 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionNumber', models.CharField(max_length=25)),
                ('TransactionDate', models.DateField()),
                ('BusinessUnit', models.CharField(max_length=100)),
                ('CustomerNumber', models.CharField(max_length=25)),
                ('CustomerName', models.CharField(blank=True, max_length=100)),
                ('ProductNumber', models.CharField(max_length=25)),
                ('Quantity', models.IntegerField()),
                ('ListPrice', models.FloatField()),
                ('TotalPrice', models.FloatField()),
                ('Discount', models.FloatField()),
                ('InvoiceAmount', models.FloatField()),
                ('SourceFileObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.FileSpace')),
                ('UniqueRunID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.RunSpace')),
            ],
        ),
    ]
