# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 22:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prof', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=100)),
                ('RunNo', models.IntegerField()),
                ('RunName', models.CharField(max_length=20)),
                ('Filetype', models.CharField(choices=[('P', 'P&L File'), ('K', 'Key File'), ('S', 'Sales Data File')], max_length=1)),
                ('TheActualFile', models.FileField(upload_to='')),
                ('Owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
