# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 02:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0002_transactiondata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filespace',
            options={'permissions': (('file_owner', 'File Owner'), ('file_edit_permission', 'File Editing Permission'), ('file_view_permission', 'File Viewing Permission'))},
        ),
        migrations.AlterModelOptions(
            name='runspace',
            options={'permissions': (('run_owner', 'File Owner'), ('run_edit_permission', 'File Editing Permission'), ('run_view_permission', 'File Viewing Permission'))},
        ),
    ]
