# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-30 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0003_auto_20170312_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filespace',
            old_name='FileDescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='filespace',
            old_name='TheActualFile',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='filespace',
            old_name='FileName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='filespace',
            old_name='UniqueRunID',
            new_name='run',
        ),
        migrations.RenameField(
            model_name='filespace',
            old_name='FileType',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='transactiondata',
            old_name='UniqueRunID',
            new_name='run',
        ),
    ]
