# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-30 02:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0005_auto_20170329_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filespace',
            old_name='Description',
            new_name='FileDescription',
        ),
        migrations.RenameField(
            model_name='filespace',
            old_name='Name',
            new_name='FileName',
        ),
        migrations.RenameField(
            model_name='filespace',
            old_name='Type',
            new_name='FileType',
        ),
    ]
