# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-19 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0006_auto_20170329_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='PnLData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LineCode', models.CharField(max_length=50)),
                ('LineDescription', models.TextField()),
                ('Amount', models.FloatField()),
                ('Period', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='filespace',
            name='FileName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transactiondata',
            name='CustomerName',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='transactiondata',
            name='CustomerNumber',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transactiondata',
            name='Department',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transactiondata',
            name='ProductNumber',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='pnldata',
            name='SourceFile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.FileSpace'),
        ),
        migrations.AddField(
            model_name='pnldata',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.RunSpace'),
        ),
    ]
