# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-21 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0009_auto_20170421_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnldata',
            name='Aggregate',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pnldata',
            name='RevorCost',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pnldata',
            name='LineCode',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
